name: Release

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-20.04
    name: Release
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Build image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          tox -e docker -- --tag=ghcr.io/ahmadsalimi/awx-ee:${{ github.event.release.tag_name }}

      - name: Apply latest tag
        run: |
         docker tag ghcr.io/ahmadsalimi/awx-ee:${{ github.event.release.tag_name }} ghcr.io/ahmadsalimi/awx-ee:latest

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push images
        run: |
         docker push ghcr.io/ahmadsalimi/awx-ee:${{ github.event.release.tag_name }}
         docker push ghcr.io/ahmadsalimi/awx-ee:latest
